import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>{`
@keyframes shadow-pulse {
  0%, 100% { box-shadow: 0 0 16px 2px rgba(220,220,255,0.7); }
  50% { box-shadow: 0 0 32px 12px rgba(220,220,255,1); }
}
@keyframes shadow-pulse-gold {
  0%, 100% { box-shadow: 0 0 16px 2px rgba(255,215,0,0.5); }
  50% { box-shadow: 0 0 24px 8px rgba(255,215,0,0.9); }
}
.shadow-pulse {
  animation: shadow-pulse 1.8s ease-in-out infinite;
}
.shadow-pulse-gold {
  animation: shadow-pulse-gold 1s ease-in-out infinite;
}
.hover-shadow-pulse:hover {
  animation: shadow-pulse 1.5s ease-in-out infinite;
}
.hover-shadow-pulse-gold:hover {
  animation: shadow-pulse-gold 1s ease-in-out infinite;
}
        `}</style>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
